#!/usr/bin/env bun

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs"
import { basename, dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const REGISTRY_ID = /^[a-z0-9]+(?:-[a-z0-9]+)*$/
const scriptDirectory = dirname(fileURLToPath(import.meta.url))
const registryDirectory = resolve(scriptDirectory, "../../../registry")
const outputPath = resolve(scriptDirectory, "../src/catalog.generated.ts")

const ids = readdirSync(registryDirectory, { withFileTypes: true })
  .filter((entry) => entry.isFile() && entry.name.endsWith(".json"))
  .map((entry) => {
    JSON.parse(readFileSync(resolve(registryDirectory, entry.name), "utf8"))
    return basename(entry.name, ".json")
  })
  .sort()

if (ids.length === 0) throw new Error("The Cafe registry is empty")
for (const id of ids) {
  if (!REGISTRY_ID.test(id)) throw new Error(`Invalid registry ID: ${id}`)
}

const generated = `// Generated by scripts/generate-catalog.ts. Do not edit.\nexport const CATALOG_IDS = ${JSON.stringify(ids, null, 2)} as const\n\nexport const CATALOG_ID_SET: Readonly<Record<string, true>> = ${JSON.stringify(Object.fromEntries(ids.map((id) => [id, true])), null, 2)}\n`

mkdirSync(dirname(outputPath), { recursive: true })
writeFileSync(outputPath, generated)
